name: Rebase

on:
  push:
    branches: ['main']

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: linhbn123/rebase-pull-requests@v1.0.1
        id: auto-rebase
        with:
          token: "${{ secrets.ENG_STD_TOKEN }}"
